### ISSUE TITLE
私有部署的版本不能创建帐号

### ISSUE THREAD

**Issue by ForeverMEhaha** [informat365/Cornerstone#2]
私有部署完成后，访问网站localhost:8888，登陆root帐号，在成员列表中添加用户，提示授权已到期

**Comment by ChinaRancho** [comment]
可以把那块代码注释掉

**Comment by 707914178** [comment]
@ForeverMEhaha 您好，我们并未重现您所描述的问题

建议重新安装，
宿主机部署版卸载 （确认mysql数据库没有其他使用）：
yum -y remove 'mysql*'
rm -rf /var/lib/mysql /var/log/mysqld.log /usr/share/mysql /tmp/install/mysql*
rm -rf /cshome

docker版卸载：
docker stop cornerstone_72 mysql_5.7
docker rm cornerstone_72 mysql_5.7
docker rmi cornerstone:72
docker rmi mysql:5.7

重新安装后，如果还有类似问题，请及时与我们沟通，我们会第一时间为您解决问题，谢谢。

![image](https://user-images.githubusercontent.com/40653000/148204850-930489b5-620e-4b28-91c7-58092c6461ea.png)

**Comment by ForeverMEhaha** [comment]
> @ForeverMEhaha 您好，我们并未重现您所描述的问题
> 
> 建议重新安装， 宿主机部署版卸载 （确认mysql数据库没有其他使用）： yum -y remove 'mysql*' rm -rf /var/lib/mysql /var/log/mysqld.log /usr/share/mysql /tmp/install/mysql* rm -rf /cshome
> 
> docker版卸载： docker stop cornerstone_72 mysql_5.7 docker rm cornerstone_72 mysql_5.7 docker rmi cornerstone:72 docker rmi mysql:5.7
> 
> 重新安装后，如果还有类似问题，请及时与我们沟通，我们会第一时间为您解决问题，谢谢。
> 
> ![image](https://user-images.githubusercontent.com/40653000/148204850-930489b5-620e-4b28-91c7-58092c6461ea.png)

重新一键部署是没什么问题了，我之前是把源码pull下来自己build部署，应该是源码里还存在权限check的代码，谢谢了

**Comment by ForeverMEhaha** [comment]
> 可以把那块代码注释掉

ok

**Comment by 707914178** [comment]
@ForeverMEhaha 您好，源码的数据库脚本我们已复现，的确会出现权限不足的情况，目前我们已经修复了这个问题，感谢您的反馈。
