### ISSUE TITLE
邮件推送链接地址的IP为啥固定是127.0.0.1呢，而不是根据实际配置的域名ip:port

### ISSUE THREAD

**Issue by changjj1143** [informat365/Cornerstone#4]
![image](https://user-images.githubusercontent.com/46027385/148355131-9021f72c-6e97-4c15-9f5c-6eabf4c5ac88.png)
实际上配置的地址为下图，导致链接无法直接打开
![image](https://user-images.githubusercontent.com/46027385/148355179-c88d51ba-07a6-4af1-8586-25cc30a4d417.png)

**Comment by 707914178** [comment]
@changjj1143 您好 需要手动修改以下参数哈～ 企业设置-参数设置-system.web.url
![image](https://user-images.githubusercontent.com/40653000/148716073-ce60e15a-27aa-4a38-a53b-0930cd148ebc.png)
![image](https://user-images.githubusercontent.com/40653000/148716134-e4b9fddb-2e79-4fd1-9a3a-ce88b8f043da.png)

**Comment by changjj1143** [comment]
> 你好，你们是怎么部署，一键安装部署还是自己打包部署的

一键安装部署

**Comment by changjj1143** [comment]
> 

谢谢，可用~
